Importing Necessary Librarys

In [5]:
!pip install scikeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
from scikeras.wrappers import KerasClassifier

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [8]:
df=pd.read_csv('/content/magic_gamma_telescope04_ (1).csv')

In [9]:
df.head()

flength    fwidth   fsize   fconc  fconc1      fsym  fm3long  fm3trans  \
0   28.7967   16.0021  2.6449  0.3918  0.1982   27.7004  22.0110   -8.2027   
1   31.6036   11.7235  2.5185  0.5303  0.3773   26.2722  23.8238   -9.9574   
2  162.0520  136.0310  4.0612  0.0374  0.0187  116.7410 -64.8580  -45.2160   
3   23.8172    9.5728  2.3385  0.6147  0.3922   27.2107  -6.4633   -7.1513   
4   75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277  28.5525   21.8393   

    falpha      dist class  
0  40.0920   81.8828     g  
1   6.3609  205.2610     g  
2  76.9600  256.7880     g  
3  10.4490  116.7370     g  
4   4.6480  356.4620     g

In [10]:
df.info

<bound method DataFrame.info of         flength    fwidth   fsize   fconc  fconc1      fsym   fm3long  \
0       28.7967   16.0021  2.6449  0.3918  0.1982   27.7004   22.0110   
1       31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   23.8238   
2      162.0520  136.0310  4.0612  0.0374  0.0187  116.7410  -64.8580   
3       23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   -6.4633   
4       75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   28.5525   
...         ...       ...     ...     ...     ...       ...       ...   
19015   21.3846   10.9170  2.6161  0.5857  0.3934   15.2618   11.5245   
19016   28.9452    6.7020  2.2672  0.5351  0.2784   37.0816   13.1853   
19017   75.4455   47.5305  3.4483  0.1417  0.0549   -9.3561   41.0562   
19018  120.5135   76.9018  3.9939  0.0944  0.0683    5.8043  -93.5224   
19019  187.1814   53.0014  3.2093  0.2876  0.1539 -167.3125 -168.4558   

       fm3trans   falpha      dist class  
0       -8.2027  40.0920   81.8828     g  
1    

In [11]:
df.describe()

flength        fwidth         fsize         fconc        fconc1  \
count  19020.000000  19020.000000  19020.000000  19020.000000  19020.000000   
mean      53.250154     22.180966      2.825017      0.380327      0.214657   
std       42.364855     18.346056      0.472599      0.182813      0.110511   
min        4.283500      0.000000      1.941300      0.013100      0.000300   
25%       24.336000     11.863800      2.477100      0.235800      0.128475   
50%       37.147700     17.139900      2.739600      0.354150      0.196500   
75%       70.122175     24.739475      3.101600      0.503700      0.285225   
max      334.177000    256.382000      5.323300      0.893000      0.675200   

               fsym       fm3long      fm3trans        falpha          dist  
count  19020.000000  19020.000000  19020.000000  19020.000000  19020.000000  
mean      -4.331745     10.545545      0.249726     27.645707    193.818026  
std       59.206062     51.000118     20.827439     26.103621     74.731787  
min     -457.916100   -331.780000   -205.894700      0.000000      1.282600  
25%      -20.586550    -12.842775    -10.849375      5.547925    142.492250  
50%        4.013050     15.314100      0.666200     17.679500    191.851450  
75%       24.063700     35.837800     10.946425     45.883550    240.563825  
max      575.240700    238.321000    179.851000     90.000000    495.561000

In [12]:
df.tail()

flength   fwidth   fsize   fconc  fconc1      fsym   fm3long  \
19015   21.3846  10.9170  2.6161  0.5857  0.3934   15.2618   11.5245   
19016   28.9452   6.7020  2.2672  0.5351  0.2784   37.0816   13.1853   
19017   75.4455  47.5305  3.4483  0.1417  0.0549   -9.3561   41.0562   
19018  120.5135  76.9018  3.9939  0.0944  0.0683    5.8043  -93.5224   
19019  187.1814  53.0014  3.2093  0.2876  0.1539 -167.3125 -168.4558   

       fm3trans   falpha      dist class  
19015    2.8766   2.4229  106.8258     h  
19016   -2.9632  86.7975  247.4560     h  
19017   -9.4662  30.2987  256.5166     h  
19018  -63.8389  84.6874  408.3166     h  
19019   31.4755  52.7310  272.3174     h

In [13]:
df.shape

(19020, 11)

In [14]:
X = df.loc[:, df.columns != 'class'].values
y = df.loc[:, 'class'].values

In [15]:
X.shape, y.shape

((19020, 10), (19020,))

In [16]:
X

array([[ 28.7967,  16.0021,   2.6449, ...,  -8.2027,  40.092 ,  81.8828],
       [ 31.6036,  11.7235,   2.5185, ...,  -9.9574,   6.3609, 205.261 ],
       [162.052 , 136.031 ,   4.0612, ..., -45.216 ,  76.96  , 256.788 ],
       ...,
       [ 75.4455,  47.5305,   3.4483, ...,  -9.4662,  30.2987, 256.5166],
       [120.5135,  76.9018,   3.9939, ..., -63.8389,  84.6874, 408.3166],
       [187.1814,  53.0014,   3.2093, ...,  31.4755,  52.731 , 272.3174]])

In [17]:
y

array(['g', 'g', 'g', ..., 'h', 'h', 'h'], dtype=object)

In [18]:
np.unique(y)

array(['g', 'h'], dtype=object)

##Label encoding

In [19]:
le = LabelEncoder()
y_en = le.fit_transform(y)

In [20]:
y

array(['g', 'g', 'g', ..., 'h', 'h', 'h'], dtype=object)

In [21]:
np.unique(y)

array(['g', 'h'], dtype=object)

##Using minmax scaler

In [22]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [23]:
X

array([[0.0743064 , 0.06241507, 0.20804258, ..., 0.51249308, 0.44546667,
        0.1630664 ],
       [0.08281491, 0.04572669, 0.17066824, ..., 0.50794422, 0.07067667,
        0.41267917],
       [0.4782407 , 0.53057937, 0.62681845, ..., 0.41654048, 0.85511111,
        0.51692609],
       ...,
       [0.21571204, 0.18538938, 0.44559432, ..., 0.5092176 , 0.33665222,
        0.51637701],
       [0.35232583, 0.29995007, 0.60691898, ..., 0.36826282, 0.94097111,
        0.82349138],
       [0.55441499, 0.20672824, 0.37492608, ..., 0.61535411, 0.5859    ,
        0.54834441]])

###using train&test data

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y_en)

In [25]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((14265, 10), (4755, 10), (14265,), (4755,))

##Model Building

In [26]:
model = Sequential()
model.add(Dense(10, input_shape=(10,), activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))



model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                110       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 231
Trainable params: 231
Non-trainable params: 0
_________________________________________________________________


In [28]:
early_stop = EarlyStopping(monitor='accuracy', patience=6)

In [29]:
X_train.shape,y_train.shape

((14265, 10), (14265,))

In [30]:
model.fit(X_train, y_train, epochs=50, batch_size=32, callbacks=[early_stop], validation_data=(X_test, y_test)) 

Epoch 1/50
446/446 [==============================] - 3s 3ms/step - loss: 0.5815 - accuracy: 0.7213 - val_loss: 0.4836 - val_accuracy: 0.7851
Epoch 2/50
446/446 [==============================] - 1s 3ms/step - loss: 0.4612 - accuracy: 0.7868 - val_loss: 0.4467 - val_accuracy: 0.7947
Epoch 3/50
446/446 [==============================] - 1s 3ms/step - loss: 0.4349 - accuracy: 0.7968 - val_loss: 0.4332 - val_accuracy: 0.8050
Epoch 4/50
446/446 [==============================] - 1s 3ms/step - loss: 0.4222 - accuracy: 0.8052 - val_loss: 0.4298 - val_accuracy: 0.8067
Epoch 5/50
446/446 [==============================] - 1s 3ms/step - loss: 0.4137 - accuracy: 0.8102 - val_loss: 0.4199 - val_accuracy: 0.8036
Epoch 6/50
446/446 [==============================] - 1s 3ms/step - loss: 0.4083 - accuracy: 0.8172 - val_loss: 0.4169 - val_accuracy: 0.8088
Epoch 7/50
446/446 [==============================] - 1s 3ms/step - loss: 0.4044 - accuracy: 0.8178 - val_loss: 0.4118 - val_accuracy: 0.8183
Epoch 

##Model Evaluation

In [31]:
model.evaluate(X_test, y_test)

149/149 [==============================] - 0s 2ms/step - loss: 0.3483 - accuracy: 0.8559


[0.34832146763801575, 0.855941116809845]

In [32]:
y_pred = model.predict(X_test).flatten()
y_pred = (y_pred>0.5).astype('int')
y_pred

149/149 [==============================] - 1s 3ms/step


array([0, 0, 0, ..., 0, 0, 1])

In [33]:
confusion_matrix(y_test, y_pred)

array([[2911,  174],
       [ 511, 1159]])

In [34]:
accuracy_score(y_test, y_pred)

0.8559411146161935

In [35]:
f1_score(y_test, y_pred)

0.7718947718947721

##Hyper parameter Tuning

In [36]:
def create_model(neurons, dropout_rate, optimizer='adam'):

	model = Sequential()
	model.add(Dense(neurons, input_shape=(15,), activation='relu'))
	model.add(Dropout(dropout_rate))
	model.add(Dense(1, activation='sigmoid'))
 
	model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
	return model

In [37]:
optimizer = ['SGD', 'RMSprop', 'Adam']
dropout_rate = [0.2, 0.3, 0.4, 0.5]
neurons = [15, 20, 25, 30]

param_grid = dict(model__optimizer=optimizer, model__dropout_rate=dropout_rate, 
                  model__neurons=neurons)

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                110       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 231
Trainable params: 231
Non-trainable params: 0
_________________________________________________________________


In [39]:
model = KerasClassifier(model=create_model, epochs=100, batch_size=10, verbose=0)

In [44]:
model

KerasClassifier(
	model=<function create_model at 0x7efe32d2d290>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=rmsprop
	loss=None
	metrics=None
	batch_size=10
	validation_batch_size=None
	verbose=0
	callbacks=None
	validation_split=0.0
	shuffle=True
	run_eagerly=False
	epochs=100
	class_weight=None
)